CREATE TABLE CUENTA_BANCO_MES(
  ID BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_CUENTA_BANCO BIGINT(20) UNSIGNED NOT NULL,
  DIA INT(10) UNSIGNED NOT NULL,
  MES INT(10) UNSIGNED NOT NULL,
  ANIO INT(10) UNSIGNED NOT NULL,
  MONTO DECIMAL(8,2) UNSIGNED NOT NULL,
  FECHA DATE NOT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL,
  FOREIGN KEY (ID_CUENTA_BANCO) REFERENCES CUENTA_BANCO(ID)
);

INSERT INTO CUENTA_BANCO_MES(ID_CUENTA_BANCO,DIA,MES,ANIO,MONTO,FECHA,ID_USUARIO_CREA,FEC_USUARIO_CREA,ID_USUARIO_MOD,FEC_USUARIO_MOD) 
SELECT ID, DAY(CURDATE()),(MONTH(CURDATE())-1) ,YEAR(CURDATE()),SALDO,CURDATE(),ID_USUARIO_CREA,FEC_USUARIO_CREA,ID_USUARIO_MOD,FEC_USUARIO_MOD 
FROM CUENTA_BANCO;

ALTER TABLE CUENTA_BANCO DROP COLUMN SALDO;

ALTER TABLE MOVIMIENTO_BANCO 
ADD FOREIGN KEY (ID_CUENTA_BANCO) REFERENCES CUENTA_BANCO(ID);

-- TABLA WALLET --

CREATE TABLE WALLET(
  ID BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL
);
--INSERTA REGISTRO EN WALLET--
INSERT INTO WALLET(NOMBRE,ID_USUARIO_CREA,FEC_USUARIO_CREA) VALUES('BILLETERA',1,CURDATE());
--RENOMBRA WALLET--
RENAME TABLE SALDO_MENSUAL TO WALLET_MES;

ALTER TABLE WALLET_MES ADD COLUMN ID_WALLET BIGINT(20) UNSIGNED NOT NULL;
UPDATE WALLET_MES SET ID_WALLET=1;
ALTER TABLE WALLET_MES ADD FOREIGN KEY (ID_WALLET) REFERENCES WALLET(ID);

CREATE TABLE MOVIMIENTO_WALLET (
  ID BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_WALLET BIGINT(20) UNSIGNED NOT NULL,
  ID_TIPO_MOVIMIENTO INT(11) UNSIGNED NOT NULL,
  DETALLE VARCHAR(50) NOT NULL,
  MONTO DECIMAL(8,2) UNSIGNED NOT NULL,
  FECHA DATE NOT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL,
  FOREIGN KEY (ID_WALLET) REFERENCES WALLET(ID)
);

--ANALIZAR Y CONTINUAR--
ALTER TABLE EGRESO ADD COLUMN ID_CATEGORIA_EGRESO INT(10) UNSIGNED NOT NULL;
ALTER TABLE EGRESO ADD COLUMN FLG_REG_DEUDA NUMERIC(1) UNSIGNED NOT NULL;
UPDATE EGRESO SET ID_CATEGORIA_EGRESO=34; 

--ATUALIZAR AQUELLOS PENDIENTE REG_DEUDA


































CREATE TABLE EGRESO (
  ID BIGINT(20) UNSIGNED NOT NULL,
  ID_TIPO_EGRESO INT(10) UNSIGNED NOT NULL,
  ID_UNIDAD_MEDIDA INT(10) UNSIGNED NOT NULL,
  NOMBRE VARCHAR(100) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI NOT NULL,
  CANTIDAD DECIMAL(8,2) UNSIGNED NOT NULL,
  PRECIO DECIMAL(8,2) UNSIGNED NOT NULL,
  TOTAL DECIMAL(8,2) UNSIGNED NOT NULL,
  DESCRIPCION VARCHAR(500) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT NULL,
  UBICACION VARCHAR(100) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT NULL,
  DIA VARCHAR(10) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI NOT NULL,
  FECHA DATE NOT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL,
  TOTAL_EGRESO DECIMAL(8,2) UNSIGNED DEFAULT NULL
);

CREATE TABLE INGRESO (
  ID BIGINT(20) UNSIGNED NOT NULL,
  ID_TIPO_INGRESO INT(10) UNSIGNED NOT NULL,
  ID_MOVIMIENTO_BANCO BIGINT(20) UNSIGNED DEFAULT NULL,
  NOMBRE VARCHAR(150) NOT NULL,
  MONTO DECIMAL(8,2) UNSIGNED NOT NULL,
  OBSERVACION VARCHAR(500) DEFAULT NULL,
  FECHA DATE NOT NULL,
  ID_ESTADO INT(10) UNSIGNED NOT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL
);

CREATE TABLE MAESTRA (
  ID BIGINT(20) UNSIGNED NOT NULL,
  ID_MAESTRA_PADRE INT(10) UNSIGNED DEFAULT NULL,
  ORDEN INT(10) UNSIGNED NOT NULL,
  NOMBRE VARCHAR(100) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI NOT NULL,
  CODIGO VARCHAR(10) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI NOT NULL,
  VALOR VARCHAR(50) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL,
  ID_TABLA INT(11) UNSIGNED DEFAULT NULL
);




CREATE TABLE RETORNO_EGRESO (
  ID BIGINT(20) UNSIGNED NOT NULL,
  ID_EGRESO BIGINT(20) UNSIGNED NOT NULL,
  ID_INGRESO BIGINT(20) UNSIGNED DEFAULT NULL,
  ID_MOVIMIENTO_BANCO BIGINT(20) UNSIGNED DEFAULT NULL,
  MONTO DECIMAL(8,2) UNSIGNED NOT NULL,
  FECHA DATE NOT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL
);


CREATE TABLE SALDO_MENSUAL (
  ID BIGINT(20) UNSIGNED NOT NULL,
  DIA INT(10) UNSIGNED NOT NULL,
  MES INT(10) UNSIGNED NOT NULL,
  ANIO INT(10) UNSIGNED NOT NULL,
  MONTO DECIMAL(8,2) UNSIGNED NOT NULL,
  FECHA DATE NOT NULL,
  ID_USUARIO_CREA INT(10) UNSIGNED NOT NULL,
  FEC_USUARIO_CREA DATE NOT NULL,
  ID_USUARIO_MOD INT(10) UNSIGNED DEFAULT NULL,
  FEC_USUARIO_MOD DATE DEFAULT NULL
);

ALTER TABLE CUENTA_BANCO
  ADD PRIMARY KEY (ID);

--
-- INDICES DE LA TABLA EGRESO
--
ALTER TABLE EGRESO
  ADD PRIMARY KEY (ID);

--
-- INDICES DE LA TABLA INGRESO
--
ALTER TABLE INGRESO
  ADD PRIMARY KEY (ID),
  ADD KEY FK_INGR_MOV_BANC (ID_MOVIMIENTO_BANCO);

--
-- INDICES DE LA TABLA MAESTRA
--
ALTER TABLE MAESTRA
  ADD PRIMARY KEY (ID);

--
-- INDICES DE LA TABLA MENSAJE
--
ALTER TABLE MENSAJE
  ADD PRIMARY KEY (ID);

--
-- INDICES DE LA TABLA MIGRATIONS
--
ALTER TABLE MIGRATIONS
  ADD PRIMARY KEY (ID);

--
-- INDICES DE LA TABLA MOVIMIENTO_BANCO
--
ALTER TABLE MOVIMIENTO_BANCO
  ADD PRIMARY KEY (ID),
  ADD KEY MOVIMIENTO_BANCO_IBFK_1 (ID_CUENTA_BANCO);

--
-- INDICES DE LA TABLA RETORNO_EGRESO
--
ALTER TABLE RETORNO_EGRESO
  ADD PRIMARY KEY (ID),
  ADD KEY FK_EGRE_RET_EGRE (ID_EGRESO);

--
-- INDICES DE LA TABLA SALDO_MENSUAL
--
ALTER TABLE SALDO_MENSUAL
  ADD PRIMARY KEY (ID);

--
-- AUTO_INCREMENT DE LAS TABLAS VOLCADAS
--

--
-- AUTO_INCREMENT DE LA TABLA CUENTA_BANCO
--
ALTER TABLE CUENTA_BANCO
  MODIFY ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT DE LA TABLA EGRESO
--
ALTER TABLE EGRESO
  MODIFY ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=964;

--
-- AUTO_INCREMENT DE LA TABLA INGRESO
--
ALTER TABLE INGRESO
  MODIFY ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;

--
-- AUTO_INCREMENT DE LA TABLA MAESTRA
--
ALTER TABLE MAESTRA
  MODIFY ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT DE LA TABLA MENSAJE
--
ALTER TABLE MENSAJE
  MODIFY ID BIGINT(20) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT DE LA TABLA MIGRATIONS
--
ALTER TABLE MIGRATIONS
  MODIFY ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT DE LA TABLA MOVIMIENTO_BANCO
--
ALTER TABLE MOVIMIENTO_BANCO
  MODIFY ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=130;

--
-- AUTO_INCREMENT DE LA TABLA RETORNO_EGRESO
--
ALTER TABLE RETORNO_EGRESO
  MODIFY ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;

--
-- AUTO_INCREMENT DE LA TABLA SALDO_MENSUAL
--
ALTER TABLE SALDO_MENSUAL
  MODIFY ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;
