DROP PROCEDURE IF EXISTS PFC_L_CUENTA_BANCO;

DELIMITER $$
CREATE PROCEDURE PFC_L_CUENTA_BANCO (
    IN FECHA_INICIO VARCHAR(10),
    IN FECHA_FIN VARCHAR(10),
    OUT R_CODIGO INTEGER, 
    OUT R_MENSAJE VARCHAR(500)
)
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	BEGIN
		GET DIAGNOSTICS CONDITION 1 R_CODIGO = RETURNED_SQLSTATE, R_MENSAJE = MESSAGE_TEXT;
		ROLLBACK;
	END;
START TRANSACTION;
    SET R_CODIGO = 0;
	SET R_MENSAJE = 'CONSULTA EXITOSA';
	SET @VSQL = "";
	IF (IFNULL(FECHA_INICIO,"")<>"" AND IFNULL(FECHA_FIN,"")<>"") THEN
	  SET @VSQL = CONCAT(@VSQL, " AND M.FEC_USUARIO_CREA>=", FECHA_INICIO, " AND M.FEC_USUARIO_CREA<=",FECHA_FIN);
	END IF;
	
	SET @MSQL = CONCAT("SELECT
    M.ID AS 'ID',
    M.NRO_CUENTA AS 'NRO_CUENTA',
    M.CCI AS 'CCI',
    M.NOMBRE AS 'NOMBRE',
    (SELECT CB.MONTO FROM CUENTA_BANCO_MES CB WHERE CB.ID=(SELECT MAX(O.ID) FROM CUENTA_BANCO_MES O WHERE O.ID_CUENTA_BANCO = M.ID)) AS MONTO,
    M.ID_USUARIO_CREA AS 'ID_USUARIO_CREA',
    M.FEC_USUARIO_CREA AS 'FEC_USUARIO_CREA',
    M.ID_USUARIO_MOD AS 'ID_USUARIO_MOD',
    M.FEC_USUARIO_MOD AS 'FEC_USUARIO_MOD'
    FROM CUENTA_BANCO M WHERE 1=1",@VSQL,
    " ORDER BY M.ID DESC");

	PREPARE STMT1 FROM @MSQL;
	EXECUTE STMT1;
	DEALLOCATE PREPARE STMT1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS PFC_L_WALLET;
DELIMITER $$
CREATE PROCEDURE PFC_L_WALLET (
    IN FECHA_INICIO VARCHAR(10),
    IN FECHA_FIN VARCHAR(10),
    OUT R_CODIGO INTEGER, 
    OUT R_MENSAJE VARCHAR(500)
)
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	BEGIN
		GET DIAGNOSTICS CONDITION 1 R_CODIGO = RETURNED_SQLSTATE, R_MENSAJE = MESSAGE_TEXT;
		ROLLBACK;
	END;
START TRANSACTION;
    SET R_CODIGO = 0;
	SET R_MENSAJE = 'CONSULTA EXITOSA';
	SET @VSQL = "";
	IF (IFNULL(FECHA_INICIO,"")<>"" AND IFNULL(FECHA_FIN,"")<>"") THEN
	  SET @VSQL = CONCAT(@VSQL, " AND M.FEC_USUARIO_CREA>=", FECHA_INICIO, " AND M.FEC_USUARIO_CREA<=",FECHA_FIN);
	END IF;
	
	SET @MSQL = CONCAT("SELECT
    M.ID AS 'ID',
    M.NOMBRE AS 'NOMBRE',
    (SELECT CB.MONTO FROM WALLET_MES CB WHERE CB.ID=(SELECT MAX(O.ID) FROM WALLET_MES O WHERE O.ID_WALLET = M.ID)) AS MONTO,
    M.ID_USUARIO_CREA AS 'ID_USUARIO_CREA',
    M.FEC_USUARIO_CREA AS 'FEC_USUARIO_CREA',
    M.ID_USUARIO_MOD AS 'ID_USUARIO_MOD',
    M.FEC_USUARIO_MOD AS 'FEC_USUARIO_MOD'
    FROM WALLET M WHERE 1=1",@VSQL,
    " ORDER BY M.ID DESC");

	PREPARE STMT1 FROM @MSQL;
	EXECUTE STMT1;
	DEALLOCATE PREPARE STMT1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS PFC_I_EGRESO;
DELIMITER $$
CREATE PROCEDURE PFC_I_EGRESO (
    IN OUT IO_ID BIGINT, 
    IN I_ID_TIPO_EGRESO INT, 
    IN I_ID_CATEGORIA_EGRESO INT, 
    IN I_ID_UNIDAD_MEDIDA INT, 
    IN I_NOMBRE VARCHAR(100), 
    IN I_CANTIDAD DECIMAL(8,2), 
    IN I_PRECIO DECIMAL(8,2), 
    IN I_TOTAL DECIMAL(8,2), 
    IN I_DESCRIPCION VARCHAR(500), 
    IN I_UBICACION VARCHAR(100), 
    IN I_DIA VARCHAR(10), 
    IN I_FECHA DATE, 
    IN I_FLG_REG_DEUDA INT,
    IN I_ID_USUARIO_CREA INT, 
    IN I_FEC_USUARIO_CREA DATE,
    IN I_COD_CATEGORIA_EGRESO INT,
    OUT O_CODIGO INTEGER, 
    OUT O_MENSAJE VARCHAR(500)
)
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	BEGIN
		GET DIAGNOSTICS CONDITION 1 R_CODIGO = RETURNED_SQLSTATE, R_MENSAJE = MESSAGE_TEXT;
		ROLLBACK;
	END;
START TRANSACTION;
    SET R_CODIGO = 0;
	SET R_MENSAJE = 'CONSULTA EXITOSA';
    
    IF I_COD_CATEGORIA_EGRESO = 1 THEN
        INSERT INTO EGRESO(ID_TIPO_EGRESO,ID_CATEGORIA_EGRESO,ID_UNIDAD_MEDIDA,NOMBRE,CANTIDAD,PRECIO,TOTAL,DESCRIPCION,UBICACION,DIA,FECHA,FLG_REG_DEUDA,ID_USUARIO_CREA,FEC_USUARIO_CREA,TOTAL_EGRESO) VALUES(I_ID_TIPO_EGRESO,I_ID_CATEGORIA_EGRESO,I_ID_UNIDAD_MEDIDA,I_NOMBRE,I_CANTIDAD,I_PRECIO,I_TOTAL,I_DESCRIPCION,I_UBICACION,I_DIA,I_FECHA,I_FLG_REG_DEUDA,I_ID_USUARIO_CREA,I_FEC_USUARIO_CREA,I_TOTAL_EGRESO);
        INSERT INTO 
    ELSEIF I_COD_CATEGORIA_EGRESO = 2 THEN

    ELSE

    END IF;
    COMMIT;
    SELECT MAX(ID) INTO IO_ID FROM EGRESO;
END IF;



    
    
END$$
DELIMITER ;